### PR TITLE
pretty

### PR DESCRIPTION
**Pull request by turanct**
Use `pretty()` instead of `show()`

### CODE REVIEW

**Comment by mathiasverraes** [comment]
nice, maybe smt can be done about the duplication in pretty and dump

**Comment by turanct** [comment]
You mean like this? https://gist.github.com/turanct/ff3ef81861b8c8acf3b5

**Comment by mathiasverraes** [comment]
Yeah, except that we lack the possibility to make private functions. For
now we could call it _prettyList instead.
I did some experiments a while back with a node js style functional module
system, which would solve this problem neatly, but I haven't gotten round
to implementing it properly.

—
Mathias Verraes
Software Consultant
Value Object Comm.V <http://value-object.com>
Blog <http://verraes.net/> - Email <mathias@verraes.net> -  Twitter
<http://twitter.com/mathiasverraes> - LinkedIn
<https://www.linkedin.com/in/mathiasverraes>

**Comment by turanct** [comment]
In some functional programming languages, you have to explicitly "export" functions from within a namespace/module... i find it elegant & clear, but i suppose it will be difficult to accomplish in php?

**Comment by mathiasverraes** [comment]
I think it's possible.

return module(@mymodule, [@somedependency], function($somedependency) {
   $myprivatefn = ...
   $mypublicfn = ...
   $otherpublicfn = ...
   return export([@mypublicfn=>$mypublicfn, @otherpublicfn =>
$otherpublicfn]);
});

The module function registers the exported functions somehow. It also finds
dependencies, injects them into the current module. Perhaps you can then
access them by calling $somedependency->functionname(), using  __call
behind the scenes.  We'd basically be abusing php's OO as dynamic
dependency mgmt.

A theoretically working example:

// foo.php
return module(@foo, [@list], function($lists) {
    $halves = $lists->map(divide(__,2), __);
    return export([@halves=>$halves]);
});

// bar.php
return module(@bar, [@foo], function($foo) {
    print(pretty($foo->halves(l(1, 2, 3))));
});


We might even do the thing that node does, where each module has it's own
dependencies, so you can have multiple versions of dependencies in your
application.



—
Mathias Verraes
Software Consultant
Value Object Comm.V <http://value-object.com>
Blog <http://verraes.net/> - Email <mathias@verraes.net> -  Twitter
<http://twitter.com/mathiasverraes> - LinkedIn
<https://www.linkedin.com/in/mathiasverraes>

**Comment by bar** [comment]
@mathiasverraes Please don't use my handle for your amusement :p

**Comment by turanct** [comment]
@mathiasverraes maybe more like this
```php
return module(@foo, [@list->map], function($map) {
    $halves = $map(divide(__,2), __);
    return export([@halves=>$halves]);
});
```
where you only import the map function from the lists module

**Comment by mathiasverraes** [comment]
@bar Oops, apologies. I hope nobody is named @foo or @list :-)

**Comment by mathiasverraes** [comment]
@turanct looks great! 

I suppose you mean  `[@list=>map]` ?  `[@list->map]` is not legal php.

You can alias functions too: `[@a=>dupe, @b=>dupe], function($dupe1, $dupe2)`

**Comment by bar** [comment]
@mathiasverraes you mean this guys? 

https://github.com/foo
https://github.com/list

**Comment by turanct** [comment]
@mathiasverraes yes, that was a typo :goat:

**Comment by turanct** [comment]
actually, there's a problem if you want to get two functions out of the same module that way...

`[@list => map, @list => reduce]` won't work

**Comment by mathiasverraes** [comment]
`module(foo, [list=>[map, reduce], other=>[map]], function($map, $reduce, $aliasedOtherMap)`

**Comment by turanct** [comment]
:+1: 

can we create an issue for the module system? PR has been hijacked by this overly superb module system :rocket:

**Comment by mathiasverraes** [comment]
No need to ask. This project prefers action over consensus!

—
Mathias Verraes
Software Consultant
Value Object Comm.V <http://value-object.com>
Blog <http://verraes.net/> - Email <mathias@verraes.net> -  Twitter
<http://twitter.com/mathiasverraes> - LinkedIn
<https://www.linkedin.com/in/mathiasverraes>

**Pull request merged**
