### PR TITLE
Add simple fixed-point combinator

### PR DESCRIPTION
**Pull request by turanct**
Yay! no more `use (&$self)`!

Y

### CODE REVIEW

**Comment by turanct** [comment]
I know, it's a little bit stupid to use the whole quicksort example for the test. Didn't see another way immediately... ideas?

**Comment by mathiasverraes** [comment]
I don't see why using quicksort is a problem?

**Comment by mathiasverraes** [comment]
IIRC for a proper Y-combinator, we can do it without using `use` at all.

**Comment by mathiasverraes** [comment]
renamed fix => recurse and added a test using `fib`

**Pull request merged**
