### PR TITLE
using the omikron test framework

### PR DESCRIPTION
**Pull request by mathiasverraes**

### CODE REVIEW

**Comment by turanct** [comment]
Very nice. I'll try to do the list tests as soon as possible

**Comment by mathiasverraes** [comment]
Do it iteratively: 
improve omikron -> write more lambdalicious tests -> use them to drive omikron improvements etc

**Comment by turanct** [comment]
Wow i guess you didn't sleep last night :rocket: such awesome, much commit!

**Comment by turanct** [comment]
omikron version 0.2.0 is what you'll want to use ;)

**Comment by turanct** [comment]
pr made to upgrade version https://github.com/mathiasverraes/lambdalicious/pull/26
"old" topics keep working

**Comment by turanct** [comment]
We're going to need something lambdalicious-specific to replace `toBe()` with, so that we can compare lists and pairs without having to use something like `expect(isequal(l(), l()), toBeTrue())` in every assertion. I assume lambdalicious could have its own custom `_toBe()` which did `isequal()` behind the scenes...

It definitely feels like there's a valid extension requirement there, for omikron. feedback welcome

**Comment by turanct** [comment]
So, what's next? delete phpunit? :rooster:

**Comment by mathiasverraes** [comment]
thanks, pure gold all of this. merged!

**Pull request merged**
