### PR TITLE
Data is just functions

### PR DESCRIPTION
**Pull request by mathiasverraes**
Reimplemented `pair()` and friends using nothing but functions. Dropped tuples for now. 

- [ ] Lists are just linked pairs
- [ ] Reintroduce tuples?

### CODE REVIEW

**Comment by turanct** [comment]
Very nice :clap: 

These are the main differences between `tuples` and `lists` as far as I know:
- `tuples` are fixed-length, `lists` are not
- a `tuple` can hold values of different types, the values in a `list` should all have the same type

Can you elaborate on "lists are just linked pairs"?

**Comment by turanct** [comment]
just a test, for lists: https://gist.github.com/turanct/e381b0bff7f29a67355c

**Comment by mathiasverraes** [comment]
>> what do you suggest?

- [ ] `lst()` 
- [ ] `l()`
- [ ] `lyst()`
- [ ] `ιiςͳ()`

**Comment by turanct** [comment]
I like l()

**Comment by turanct** [comment]
turns out that changing a datastructure is not as simple as it looks :-)

fail

**Comment by turanct** [comment]
i'm almost there. status:

* lists are implemented as pairs
* there's a list constructor called `@λ_list`
* `l(a, b, c)` is syntactic sugar for `pair(a, pair(b, pair(c, @λ_list)));`
* there's a cast from array to list `arrayl([a, b, c])`, so that we can use ...$arguments in function definitions, and work with those arguments by casting them to a list
* i'm glad there are unit tests, refactoring is so fluent

**Comment by turanct** [comment]
note to self:

* clean up `islist()`: replace `=== @λ_list` in there with `=== l()`, simplify, use lambdalicious code style
* replace `arrayl()` with `al()`? We can then also have the opposite `la()`
* replace `func_get_args()` with `al(func_get_args())` so we have lambdalistjes everywhere

**Comment by turanct** [comment]
Everything is functions now! i just need to clean up some docblocks, i'll do that tonight, then i'll add to this pull request. yay! :rocket:

**Comment by turanct** [comment]
lambdalistjes are pull requsted! https://github.com/mathiasverraes/lambdalicious/pull/18

**Comment by mathiasverraes** [comment]
@turanct Please add yourself as author to composer.json

**Pull request merged**
